version: '3'

services:
  ledfx:
    image: shirom/ledfx 
#    image: ledfx/ledfx 
    container_name: ledfx
    environment: 
#      - HOST=192.168.1.63
      - FORMAT=-r 44100 -f S16_LE -c 2
      - SQUEEZE=1
    ports:
      - 8888:8888
    volumes:
      - ~/ledfx-config:/app/ledfx-config
      - ~/audio:/app/audio
    devices:
      - /dev/snd:/dev/snd
